#ifndef KIT_Z_STATE_SMITH_IFSM_H_
#define KIT_Z_STATE_SMITH_IFSM_H_
/*------------------------------------------------------------------------------
 * Copyright Integer Fox Authors
 *
 * Distributed under the BSD 3 Clause License. See the license agreement at:
 * https://github.com/Integerfox/kit.core/blob/main/LICENSE
 *
 * Redistributions of the source code must retain the above copyright notice.
 *----------------------------------------------------------------------------*/
/** @file */

///
namespace Kit {
///
namespace Z {
///
namespace StateSmith {

/** This class provides an abstract interface the exposes the public methods
    of a FSM generated by StateSmith.  The primary purpose of this interface is
    to support having parent classes (to the auto-generated FSM class) to have
    access to its methods.

    This interface is NOT thread safe.  It is the application's responsibility
    to ensure that access to the FSM instance is properly synchronized.

    NOTE: The `nqbp/other/genfsm2.py` script is required to 'patch' the 
          generated code to use this class
 */
template <typename EventId, typename StateId>
class IFsm
{
public:
    /// Function to convert a state ID to a string
    virtual const char* stateIdToString( StateId stateId ) = 0;

    /// Function to convert an event ID to a string
    virtual const char* eventIdToString( EventId eventId ) = 0;

    /// Function to get the current state ID
    virtual StateId getCurrentStateId() = 0;

    /// Returns the FSM 'name'
    virtual const char* getFsmName() = 0;

    // Dispatches an event to the state machine.
    virtual void dispatchEvent( EventId eventId ) = 0;

public:
    /// Ensure the destructor is virtual
    virtual ~IFsm() {}
};


}  // end namespaces
}
}
#endif  // end header latch
