#ifndef KIT_TSHELL_ISECURITY_H_
#define KIT_TSHELL_ISECURITY_H_
/*------------------------------------------------------------------------------
 * Copyright Integer Fox Authors
 *
 * Distributed under the BSD 3 Clause License. See the license agreement at:
 * https://github.com/Integerfox/kit.core/blob/main/LICENSE
 *
 * Redistributions of the source code must retain the above copyright notice.
 *----------------------------------------------------------------------------*/
/** @file */

#include "kit_config.h"
#include <stdint.h>


///
namespace Kit {
///
namespace TShell {

/** This type is used to represent security permissions. It is application
    responsible to define the specific permissions and their meanings.
 */
#ifndef OPTION_KIT_TSHELL_SECURITY_PERMISSION_TYPE
using Permissions_T = uint32_t;

#else
using Permissions_T = OPTION_KIT_TSHELL_SECURITY_PERMISSION_TYPE;
#endif

/** The permission value used as the constructor defaults for KIT TShell commands */
#ifndef OPTION_KIT_TSHELL_SECURITY_DEFAULT_PERMISSIONS
#define OPTION_KIT_TSHELL_SECURITY_DEFAULT_PERMISSIONS 0
#endif


/** This abstract class defines the interface validating that is okay to execute
    a TShell command.  The underlying security model is specific to the application
    and is not defined by this interface.
*/
class ISecurity
{
public:
    /** This method evaluates the current security state and returns true/false
        if the specified permission level is sufficient to execute a command.

        The 'queryOnly' parameter is used to indicate that the caller is only
        interested in querying the security state and not actually executing
        the command.  A use case for this is the TShell 'help' command that
        only displays authorized commands but does not execute them.
     */
    virtual bool isAuthorized( Permissions_T permission,
                               const char*   entireCommandString,
                               bool          queryOnly = false ) noexcept = 0;


    /** This method is used to suppress the TShell outputs until the session
        has been 'authenticated'.  This can be useful in scenarios where you
        want to prevent unauthorized users from seeing certain output until they
        have successfully authenticated.  The outputs that are suppressed - when
        the method returns true - include, but are not limited to, the
        following:
        
            - The TShell prompt
            - The TShell welcome and farewell messages
            - The TShell command error messages (e.g. unrecognized command, bad
              syntax, etc.)

        NOTE: Output generated by individual commands (i.e. via the IContext's
              writeFrame() method) is NOT automatically suppressed by this method.
              It is the responsibility of individual commands to check the 
              security state (via isSilent()) and suppress their output as needed.
     */
    virtual bool isSilent() noexcept = 0;

public:
    /// Virtual destructor
    virtual ~ISecurity() = default;
};


}  // end namespaces
}
#endif  // end header latch
