#ifndef DM_TRANSACTION_FOOT_H_
#define DM_TRANSACTION_FOOT_H_
/*------------------------------------------------------------------------------
 * Copyright Integer Fox Authors
 *
 * Distributed under the BSD 3 Clause License. See the license agreement at:
 * https://github.com/Integerfox/kit.core/blob/main/LICENSE
 *
 * Redistributions of the source code must retain the above copyright notice.
 *----------------------------------------------------------------------------*/
/** @file */

#include <stdint.h>
#include <string.h>

///
namespace Dm {
///
namespace Transaction {

/** Data structure used to exchange data between a Client and Server for the
    'Foo' transaction.

    The following are needed because the structure is used as a 'data source'
    for a Model Point:
    ----------------------------------------------------------------------------
    - The comparison operation
    - The copy constructor and copy operator are implemented to ensure that
      any 'pad' bytes in the structure get zero'd out.  This is desired because
      the default 'comparison operation' in the DM framework uses memcmp.  A
      more sophisticated comparision approach can be used - but it requires the
      concrete Model Point to supply/implement the comparison method.
 */
struct Foo_T
{
    int32_t upperLimit;    //!< IN:  Upper limit for the random number generator
    int32_t lowerLimit;    //!< IN:  Lower limit for the random number generator
    int32_t randomNumber;  //!< OUT: Random number generated by the Server and sent to the Client
    bool    isValid;       //!< OUT: Indicates whether the 'randomNumber' value is valid (true) or not (false)


    /// Constructor (to ensure any pad bytes get zero'd -->needed for brute force compare operation)
    Foo_T()
    {
        memset( (void*)this, 0, sizeof( Foo_T ) );
    }

    /// Copy Constructor (to ensure any pad bytes get zero'd)
    Foo_T( const Foo_T& other )
    {
        memcpy( (void*)this, (void*)&other, sizeof( Foo_T ) );
    }

    /// Constructor - all arguments
    Foo_T( int32_t upperLimit,
           int32_t lowerLimit,
           int32_t randomNumber,
           bool    isValid )
    {
        memset( (void*)this, 0, sizeof( Foo_T ) );
        this->upperLimit   = upperLimit;
        this->lowerLimit   = lowerLimit;
        this->randomNumber = randomNumber;
        this->isValid      = isValid;
    }

    /// Comparison operator (for DM support)
    bool operator==( Foo_T const& other ) const
    {
        return memcmp( this, &other, sizeof( Foo_T ) ) == 0;
    }

    /// Copy operator
    Foo_T& operator=( const Foo_T& other )
    {
        memcpy( (void*)this, (void*)&other, sizeof( Foo_T ) );
        return *this;
    }
};

}  // end namespaces
}
#endif  // end header latch
