name: Build Linux GCC
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  gcc_linux_build:
    name: GCC Compiler Linux Build
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        run: |
          git config --global core.autocrlf false
          git config --global core.safecrlf false
      - uses: actions/checkout@v2

      # Python setup (with gcovr)
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      - run: pip install -r top/gha-requirements.txt

      # Ninja setup
      - uses: seanmiddleditch/gha-setup-ninja@master
        with:
          version: '1.11.1'

      # Installs 
      - name: Install Doxygen
        uses: ssciwr/doxygen-install@v1
        with:
          version: "1.10.0"
      
      # Install Graphviz
      - name: Install Graphviz
        uses: tlylt/install-graphviz@v1
         
      # This step is commented out, but can be used for debugging purposes.
      #- name: Setup tmate session 
      # uses: mxschmitt/action-tmate@v3

      # Run Doxygen 
      - name: Run Doxygen
        run: |
          echo "Running Doxygen..."
          rm -rf ./docs/html
          mkdir -p ./docs/html
          cd ./top
          ./run_doxygen.py ${{ github.ref_name }} ${{ github.run_number }} nochm
        
      # Build PRs
      - name: Run build script - for PRs
        if: github.event_name == 'pull_request'
        run: |
          echo "Running build script for PRs..."
          ./top/gha_linux_gcc-host.sh 0 

      # Build Stable branches
      - name: Run build script - for stable branches
        if: github.event_name != 'pull_request'
        run: |
          echo "Running build script for stable branches..."
          ./top/gha_linux_gcc-host.sh ${{ github.run_number }} ${{ github.ref_name }}

      # Publish Doxygen documentation (but only when building main branch)
      - name: Publish Doxygen documentation
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/publish
