name: Build Linux GCC
on:
  workflow_call:
    inputs:
      event_name:
        required: true
        type: string
      run_number:
        required: true
        type: string
      ref_name:
        required: true
        type: string

permissions:
  contents: write

jobs:
  gcc_linux_build:
    name: GCC Compiler Linux Build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      # Checkout code
      - name: Checkout code
        run: |
          git config --global core.autocrlf false
          git config --global core.safecrlf false
      - uses: actions/checkout@v2

      # Python setup (with gcovr)
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      - run: pip install -r top/gha-requirements.txt

      # Setup lcov for code coverage
      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1
        
      # Ninja setup
      - uses: seanmiddleditch/gha-setup-ninja@master
        with:
          version: '1.11.1'

      # Installs 
      - name: Install Doxygen
        uses: ssciwr/doxygen-install@v1
        with:
          version: "1.10.0"
      
      # Install Graphviz
      - name: Install Graphviz
        uses: tlylt/install-graphviz@v1
         
      # This step is commented out, but can be used for debugging purposes.
      #- name: Setup tmate session 
      # uses: mxschmitt/action-tmate@v3

      # Run Doxygen 
      - name: Run Doxygen
        run: |
          echo "Running Doxygen..."
          rm -rf ./docs/publish/doxygen
          mkdir -p ./docs/publish/doxygen
          cd ./top
          ./run_doxygen.py ${{ inputs.ref_name }} ${{ inputs.run_number }} nochm
        
      # Build PRs
      - name: Run build script - for PRs
        if: inputs.event_name == 'pull_request'
        run: |
          echo "Running build script for PRs..."
          ./top/gha_linux_gcc-host.sh 0 

      # Build Stable branches
      - name: Run build script - for stable branches
        if: inputs.event_name != 'pull_request'
        run: |
          echo "Running build script for stable branches..."
          ./top/gha_linux_gcc-host.sh ${{ inputs.run_number }} ${{ inputs.ref_name }}

      # Publish Doxygen documentation (but only when building main branch)
      - name: Publish Doxygen documentation
        if: inputs.event_name != 'pull_request' && inputs.ref_name == 'main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/publish
